baseURL = "https://glamp.github.io/blog/"
languageCode = "en-us"
title = "The Yaksis"
theme = "hugo-cactus-theme"

googleAnalytics = ""

[params]
name = "Greg Lamp"
description = "Greg's blog"
bio = "Author of many abandoned open-source libraries that once showed promise, former founder of Yhat (YC W15), currently Director of Engineering at Alteryx."
twitter = "theglamp"
enableRSS = true
iconFont = "mono-social"
# The social icons can be styled differently if you use mono as font - circle, rounded, or empty
socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
twitter  = "https://www.twitter.com/theglamp"
github   = "https://www.github.com/glamp"
